In [20]:
# Logistic regression 
xdata = [
    [1,2],
    [2,1],
    [2,3],
    [4,1],
    [5,1],
    [4,2],
    [6,4],
]
ydata = [
    [0],
    [0],
    [0],
    [1],
    [1],
    [0],
    [1]   
]
# x, y => 0 or 1 
import tensorflow as tf
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [21]:
W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [22]:
# Hypothesis sigmoid 
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * 
                      tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01) \
    .minimize(cost)

In [23]:
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32) 
# h >= 0.5 => 1, h < 0.5 => 0
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y) \
                                 , dtype=tf.float32))

In [30]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for s in range(2000):
    cost_val, _ = sess.run([cost, train], \
                           feed_dict={X:xdata, Y:ydata})
    if s % 200 == 0:
        print(s, cost_val)
        #pass
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict={X:xdata, Y:ydata})
    print(h, c, a)

0 1.4777031
[[0.0557886 ]
 [0.16701385]
 [0.01464293]
 [0.14611962]
 [0.13651074]
 [0.04451391]
 [0.00293839]] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 0.5714286
[[0.05778854]
 [0.17387322]
 [0.01559017]
 [0.15717937]
 [0.14933339]
 [0.0486673 ]
 [0.0033993 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 0.5714286
[[0.05983318]
 [0.18087336]
 [0.01658664]
 [0.16877683]
 [0.1629745 ]
 [0.05313522]
 [0.00392606]] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 0.5714286
[[0.06192095]
 [0.18800437]
 [0.01763332]
 [0.18089686]
 [0.17742237]
 [0.05792938]
 [0.00452657]] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 0.5714286
[[0.06405005]
 [0.19525535]
 [0.01873099]
 [0.19351871]
 [0.19265479]
 [0.06306005]
 [0.00520938]] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 0.5714286
[[0.06621841]
 [0.20261464]
 [0.01988025]
 [0.20661612]
 [0.20863871]
 [0.06853574]
 [0.00598361]] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 0.5714286
[[0.06842381]
 [0.21006967]
 [0.02108151]
 [0.22015749]
 [0.2253301 ]
 [0.07

[[0.18677719]
 [0.54878366]
 [0.13925779]
 [0.8193906 ]
 [0.89756507]
 [0.62330765]
 [0.45087224]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.18668891]
 [0.54884505]
 [0.13925081]
 [0.8196273 ]
 [0.89777416]
 [0.6236474 ]
 [0.4514896 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.1865973 ]
 [0.5488997 ]
 [0.1392394 ]
 [0.81985676]
 [0.89797753]
 [0.6239747 ]
 [0.4520866 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.18650255]
 [0.5489479 ]
 [0.1392237 ]
 [0.8200792 ]
 [0.8981756 ]
 [0.62429005]
 [0.4526642 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.18640476]
 [0.5489899 ]
 [0.13920395]
 [0.820295  ]
 [0.8983685 ]
 [0.624594  ]
 [0.45322308]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.18630406]
 [0.54902583]
 [0.13918023]
 [0.82050437]
 [0.8985563 ]
 [0.62488693]
 [0.4537637 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.18620056]
 [0.54905605]
 [0.1391527 ]
 [0.82070756]
 [0.8987393 ]
 [0.6251691 ]
 [0.

[[0.16774282]
 [0.53820723]
 [0.12731001]
 [0.8298718 ]
 [0.9089196 ]
 [0.63313216]
 [0.4748179 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.16759443]
 [0.5380906 ]
 [0.12720713]
 [0.82990867]
 [0.9089715 ]
 [0.6331398 ]
 [0.47489432]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.16744627]
 [0.5379739 ]
 [0.1271044 ]
 [0.8299454 ]
 [0.9090232 ]
 [0.63314724]
 [0.47497055]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.16729833]
 [0.5378571 ]
 [0.12700184]
 [0.829982  ]
 [0.9090747 ]
 [0.6331546 ]
 [0.4750467 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.16715059]
 [0.5377404 ]
 [0.12689942]
 [0.83001846]
 [0.90912616]
 [0.6331618 ]
 [0.47512272]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.16700302]
 [0.5376235 ]
 [0.12679711]
 [0.83005464]
 [0.9091775 ]
 [0.6331688 ]
 [0.47519845]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.1668557 ]
 [0.5375067 ]
 [0.12669502]
 [0.8300908 ]
 [0.90922856]
 [0.6331758 ]
 [0.

[[0.14990959]
 [0.522742  ]
 [0.1150751 ]
 [0.83379483]
 [0.9147943 ]
 [0.6335066 ]
 [0.48452374]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.14978707]
 [0.5226252 ]
 [0.11499213]
 [0.8338187 ]
 [0.9148327 ]
 [0.63350636]
 [0.48459658]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.14966471]
 [0.52250844]
 [0.11490929]
 [0.83384246]
 [0.91487104]
 [0.633506  ]
 [0.48466966]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.14954256]
 [0.52239174]
 [0.11482655]
 [0.8338663 ]
 [0.91490924]
 [0.63350564]
 [0.48474246]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.14942053]
 [0.52227503]
 [0.11474395]
 [0.8338899 ]
 [0.9149474 ]
 [0.6335053 ]
 [0.48481542]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.1492987 ]
 [0.5221583 ]
 [0.11466149]
 [0.8339135 ]
 [0.9149855 ]
 [0.63350487]
 [0.4848884 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.14917707]
 [0.5220417 ]
 [0.11457921]
 [0.83393705]
 [0.9150235 ]
 [0.6335045 ]
 [0.

[[0.13614257]
 [0.508595  ]
 [0.10584411]
 [0.83620584]
 [0.918953  ]
 [0.6332341 ]
 [0.4934257 ]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.1360388 ]
 [0.50847995]
 [0.10577522]
 [0.8362219 ]
 [0.9189831 ]
 [0.63323   ]
 [0.49349856]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.13593513]
 [0.50836486]
 [0.10570639]
 [0.83623767]
 [0.9190132 ]
 [0.63322586]
 [0.49357134]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.13583158]
 [0.5082498 ]
 [0.10563769]
 [0.8362535 ]
 [0.9190432 ]
 [0.63322175]
 [0.49364424]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.1357282 ]
 [0.5081347 ]
 [0.10556907]
 [0.8362692 ]
 [0.91907316]
 [0.6332176 ]
 [0.49371704]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.13562493]
 [0.5080197 ]
 [0.10550056]
 [0.83628494]
 [0.9191031 ]
 [0.63321334]
 [0.49378982]] [[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]] 0.5714286
[[0.13552183]
 [0.5079047 ]
 [0.10543215]
 [0.8363006 ]
 [0.9191329 ]
 [0.6332092 ]
 [0.

[[0.12467407]
 [0.4950144 ]
 [0.09828769]
 [0.83773947]
 [0.92217183]
 [0.6325745 ]
 [0.5020676 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.12458472]
 [0.49490133]
 [0.09822927]
 [0.83774954]
 [0.922196  ]
 [0.6325675 ]
 [0.50214   ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.12449543]
 [0.49478823]
 [0.0981709 ]
 [0.83775955]
 [0.9222201 ]
 [0.6325606 ]
 [0.5022122 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.12440628]
 [0.49467513]
 [0.09811255]
 [0.83776945]
 [0.9222442 ]
 [0.63255364]
 [0.50228447]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.12431722]
 [0.4945621 ]
 [0.09805432]
 [0.8377794 ]
 [0.9222683 ]
 [0.6325466 ]
 [0.5023568 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.12422829]
 [0.4944491 ]
 [0.09799619]
 [0.8377893 ]
 [0.9222923 ]
 [0.63253963]
 [0.502429  ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.12413945]
 [0.49433616]
 [0.09793815]
 [0.83779913]
 [0.9223162 ]
 [0.6325326 

[[0.11490349]
 [0.4819107 ]
 [0.09193278]
 [0.8386436 ]
 [0.9247321 ]
 [0.63163424]
 [0.5104787 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.11482554]
 [0.48179987]
 [0.09188235]
 [0.83864915]
 [0.92475176]
 [0.6316252 ]
 [0.51055014]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.1147477 ]
 [0.48168904]
 [0.09183202]
 [0.83865464]
 [0.92477155]
 [0.63161606]
 [0.51062167]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.11466993]
 [0.48157826]
 [0.0917817 ]
 [0.8386602 ]
 [0.9247912 ]
 [0.63160694]
 [0.51069295]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.11459226]
 [0.4814675 ]
 [0.0917315 ]
 [0.83866566]
 [0.92481077]
 [0.6315979 ]
 [0.5107645 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.11451469]
 [0.4813567 ]
 [0.09168129]
 [0.838671  ]
 [0.92483044]
 [0.6315887 ]
 [0.5108358 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.11443719]
 [0.48124596]
 [0.09163114]
 [0.8386764 ]
 [0.9248499 ]
 [0.6315795 

 [0.5197537 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.10532391]
 [0.46745884]
 [0.08576151]
 [0.8391104 ]
 [0.92707545]
 [0.63030773]
 [0.5198238 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.10525643]
 [0.46735078]
 [0.08571819]
 [0.83911204]
 [0.92709136]
 [0.6302968 ]
 [0.51989406]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.10518899]
 [0.4672428 ]
 [0.08567491]
 [0.8391137 ]
 [0.92710733]
 [0.63028586]
 [0.51996416]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.10512162]
 [0.46713477]
 [0.0856317 ]
 [0.8391153 ]
 [0.9271231 ]
 [0.6302749 ]
 [0.5200342 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.10505431]
 [0.46702674]
 [0.0855885 ]
 [0.8391168 ]
 [0.927139  ]
 [0.63026386]
 [0.5201043 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.10498708]
 [0.46691874]
 [0.08554537]
 [0.8391184 ]
 [0.9271548 ]
 [0.6302529 ]
 [0.5201743 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.10491996]

[[0.09787925]
 [0.45496726]
 [0.0809942 ]
 [0.8391439 ]
 [0.92878133]
 [0.6289522 ]
 [0.5279515 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09781934]
 [0.45486176]
 [0.08095589]
 [0.83914286]
 [0.92879456]
 [0.62894   ]
 [0.5280202 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09775947]
 [0.45475638]
 [0.0809176 ]
 [0.83914185]
 [0.92880785]
 [0.62892777]
 [0.5280888 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09769966]
 [0.454651  ]
 [0.08087939]
 [0.8391407 ]
 [0.92882115]
 [0.62891555]
 [0.5281575 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0976399 ]
 [0.4545456 ]
 [0.08084118]
 [0.83913964]
 [0.9288345 ]
 [0.6289033 ]
 [0.52822614]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
1000 0.38170007
[[0.09758022]
 [0.4544403 ]
 [0.08080302]
 [0.83913857]
 [0.9288477 ]
 [0.62889105]
 [0.5282948 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09752058]
 [0.45433494]
 [0.08076492]
 [0.83913743]
 [0.928860

 [0.53604686]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09108783]
 [0.44248298]
 [0.07665614]
 [0.8388903 ]
 [0.93025005]
 [0.6274293 ]
 [0.5361143 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09103442]
 [0.4423804 ]
 [0.07662204]
 [0.8388872 ]
 [0.9302613 ]
 [0.62741613]
 [0.53618145]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09098107]
 [0.44227782]
 [0.07658798]
 [0.83888406]
 [0.9302725 ]
 [0.62740296]
 [0.5362487 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09092776]
 [0.44217527]
 [0.07655393]
 [0.83888084]
 [0.9302838 ]
 [0.6273898 ]
 [0.5363158 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09087451]
 [0.44207275]
 [0.07651995]
 [0.8388777 ]
 [0.93029493]
 [0.6273767 ]
 [0.5363831 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0908213 ]
 [0.44197023]
 [0.07648594]
 [0.8388744 ]
 [0.9303061 ]
 [0.62736344]
 [0.5364502 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.09076814]

 [0.54402167]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0850157 ]
 [0.4303423 ]
 [0.07277674]
 [0.8384086 ]
 [0.9314947 ]
 [0.62580526]
 [0.54408735]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.08496778]
 [0.43024257]
 [0.07274609]
 [0.8384037 ]
 [0.9315042 ]
 [0.6257913 ]
 [0.54415286]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.08491994]
 [0.43014285]
 [0.07271547]
 [0.8383988 ]
 [0.93151385]
 [0.6257774 ]
 [0.5442185 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.08487211]
 [0.4300432 ]
 [0.0726849 ]
 [0.83839405]
 [0.9315233 ]
 [0.62576354]
 [0.54428416]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.08482433]
 [0.42994356]
 [0.07265434]
 [0.8383891 ]
 [0.93153286]
 [0.62574965]
 [0.54434973]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.08477662]
 [0.42984396]
 [0.07262383]
 [0.8383843 ]
 [0.9315424 ]
 [0.62573576]
 [0.54441524]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0847289 ]

 [0.55249834]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07908049]
 [0.4174894 ]
 [0.06897373]
 [0.8376812 ]
 [0.9326518 ]
 [0.62394774]
 [0.55256224]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07903768]
 [0.41739294]
 [0.06894624]
 [0.837675  ]
 [0.93266   ]
 [0.62393326]
 [0.552626  ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07899489]
 [0.41729644]
 [0.06891876]
 [0.8376687 ]
 [0.9326682 ]
 [0.6239188 ]
 [0.5526897 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07895213]
 [0.41719997]
 [0.06889129]
 [0.83766246]
 [0.93267626]
 [0.6239043 ]
 [0.55275327]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07890942]
 [0.41710356]
 [0.06886388]
 [0.83765614]
 [0.93268436]
 [0.6238899 ]
 [0.55281705]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07886676]
 [0.41700718]
 [0.06883645]
 [0.8376499 ]
 [0.93269247]
 [0.62387544]
 [0.55288076]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07882412]

 [1.]] 0.85714287
[[0.07461452]
 [0.40711734]
 [0.06609774]
 [0.83695215]
 [0.9334872 ]
 [0.62235403]
 [0.5594247 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07457533]
 [0.40702355]
 [0.0660724 ]
 [0.83694506]
 [0.9334943 ]
 [0.6223392 ]
 [0.55948687]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0745362 ]
 [0.40692985]
 [0.06604715]
 [0.83693796]
 [0.9335016 ]
 [0.62232447]
 [0.5595491 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07449709]
 [0.40683606]
 [0.06602188]
 [0.83693075]
 [0.9335087 ]
 [0.6223097 ]
 [0.5596112 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07445799]
 [0.4067423 ]
 [0.06599662]
 [0.8369236 ]
 [0.93351597]
 [0.62229484]
 [0.55967313]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07441896]
 [0.4066486 ]
 [0.0659714 ]
 [0.83691645]
 [0.9335231 ]
 [0.62228006]
 [0.5597353 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07437991]
 [0.40655488]
 [0.06594616]
 [0.8369093 ]
 [0.9335

 [0.56683636]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0700549 ]
 [0.39585596]
 [0.06314146]
 [0.8360345 ]
 [0.9343124 ]
 [0.6205344 ]
 [0.56689656]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.07001927]
 [0.39576516]
 [0.06311826]
 [0.8360265 ]
 [0.9343187 ]
 [0.6205194 ]
 [0.56695694]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06998368]
 [0.39567444]
 [0.06309509]
 [0.8360187 ]
 [0.9343252 ]
 [0.62050444]
 [0.56701744]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
1600 0.34638306
[[0.06994811]
 [0.39558366]
 [0.06307192]
 [0.83601075]
 [0.93433154]
 [0.62048936]
 [0.56707764]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06991257]
 [0.39549294]
 [0.06304879]
 [0.83600295]
 [0.9343378 ]
 [0.6204744 ]
 [0.567138  ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06987704]
 [0.39540228]
 [0.06302564]
 [0.835995  ]
 [0.9343441 ]
 [0.6204593 ]
 [0.56719816]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.857142

 [1.]] 0.85714287
[[0.06570517]
 [0.38443372]
 [0.06029548]
 [0.8349851 ]
 [0.9350785 ]
 [0.6185997 ]
 [0.57449657]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06567277]
 [0.38434607]
 [0.06027417]
 [0.83497655]
 [0.93508416]
 [0.6185846 ]
 [0.574555  ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0656404 ]
 [0.3842584 ]
 [0.06025286]
 [0.8349681 ]
 [0.93508977]
 [0.6185693 ]
 [0.5746132 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06560807]
 [0.38417077]
 [0.06023159]
 [0.8349596 ]
 [0.93509537]
 [0.6185542 ]
 [0.57467157]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06557576]
 [0.3840832 ]
 [0.06021032]
 [0.83495116]
 [0.93510115]
 [0.61853904]
 [0.5747301 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06554345]
 [0.38399562]
 [0.06018907]
 [0.83494264]
 [0.93510664]
 [0.61852384]
 [0.5747884 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06551119]
 [0.38390812]
 [0.06016784]
 [0.8349341 ]
 [0.9351

[[0.06183112]
 [0.37366292]
 [0.05773288]
 [0.83389884]
 [0.9357484 ]
 [0.61669695]
 [0.5816802 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06180149]
 [0.37357822]
 [0.05771317]
 [0.83388996]
 [0.93575346]
 [0.61668164]
 [0.5817367 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06177188]
 [0.37349367]
 [0.05769347]
 [0.83388114]
 [0.9357586 ]
 [0.61666644]
 [0.58179325]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06174229]
 [0.37340906]
 [0.05767378]
 [0.83387226]
 [0.9357637 ]
 [0.61665124]
 [0.5818499 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06171273]
 [0.37332445]
 [0.0576541 ]
 [0.8338634 ]
 [0.9357687 ]
 [0.616636  ]
 [0.58190626]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06168318]
 [0.37323993]
 [0.05763442]
 [0.8338545 ]
 [0.93577385]
 [0.6166207 ]
 [0.58196265]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.06165366]
 [0.3731554 ]
 [0.05761476]
 [0.8338456 ]
 [0.935779  ]
 [0.6166055 

[[0.0588012 ]
 [0.3648222 ]
 [0.05570611]
 [0.8329452 ]
 [0.93626815]
 [0.6150808 ]
 [0.58758926]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.05877366]
 [0.36474004]
 [0.05568757]
 [0.8329361 ]
 [0.93627286]
 [0.6150655 ]
 [0.5876442 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.05874612]
 [0.36465794]
 [0.05566904]
 [0.83292705]
 [0.93627757]
 [0.61505026]
 [0.5876992 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.0587186 ]
 [0.36457586]
 [0.05565053]
 [0.8329179 ]
 [0.9362823 ]
 [0.61503506]
 [0.58775413]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.05869111]
 [0.36449376]
 [0.05563204]
 [0.8329088 ]
 [0.936287  ]
 [0.61501974]
 [0.5878089 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.05866362]
 [0.36441168]
 [0.05561353]
 [0.83289975]
 [0.9362917 ]
 [0.6150045 ]
 [0.5878638 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.85714287
[[0.05863617]
 [0.3643297 ]
 [0.05559504]
 [0.8328906 ]
 [0.9362964 ]
 [0.6149892 